name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create fake APK
        run: |
          mkdir build
          echo "MatveyCraft APK" > build/app-debug.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: matveycraft-apk
          path: build/app-debug.apk
